# Site
name: "tutorial website"
title: "tutorial website"
description: "Ini adalah kumpulan tutorial website"
logo: 'assets/images/logo.png'
favicon: 'assets/images/postkomik.jpg'
baseurl: ''
google_analytics: 'UA-178648244-4'
disqus: 'tutorialwebsite-1'

include: ["_pages"]
permalink: /:title/

# Authors
authors:
  
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: Ahmadalwy@gmail.com
    web: https://postkomik.github.io
    twitter: https://twitter.com/OnlienPejuang
    description: "Belajar menjadi baik dan pantang menyerah "
    
  kaisan:
    name: Kaisan
    display_name: Kaisan
    avatar: 'assets/images/postkomik.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: kmkaisan1@gmail.com
    web: https://tutorialwebsite.github.io/
    twitter: https://twitter.com/
    description: "gw ganteng jadi jangan kaget dahulu kalo naksir yah"
    

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412xxxxxx"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
